# Generated by Django 2.2.16 on 2020-10-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midnightoil',
            name='learnt_date',
            field=models.DateTimeField(default=None, verbose_name='learnt_date'),
        ),
    ]
