# Generated by Django 2.2.16 on 2020-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20201016_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midnightoil',
            name='learnt_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='learnt_date'),
        ),
    ]
