# Generated by Django 2.2.16 on 2020-10-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0003_auto_20201016_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midnightoil',
            name='learnt_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='learnt_date'),
        ),
    ]
