# Generated by Django 2.2.16 on 2020-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0004_auto_20201016_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='midnightoil',
            name='already_know',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
